### PR TITLE
Add ability to dynamically define interceptors. 

### PR DESCRIPTION
**Pull request by adam-26**
Formalize interceptor processing order.

This pull request adds additional features that allow interceptors to be defined in methods, this is important when the order that interceptors are executed is important.

I've refactored a little, and attempted to standardize whitespace.

### CODE REVIEW

**Comment by adam-26** [comment]
All tests were passing locally. I'll look at the build server errors next week, no time this week.

**Comment by jvmlet** [comment]
Hi
Have you tried to hook up the bean `FactoryBean<MyDynamicallyCreatedServiceInterceptor>` into the application context and then 

````
	 @GRpcService(interceptors = { MyDynamicallyCreatedServiceInterceptor.class })
 public  class GreeterService extends  GreeterGrpc.GreeterImplBase{
	     // ommited
 }
````
I think it will work out of the box.....
According to ordering, I would stick to `@Ordered` annotation from standard spring API and then just sort the interceptors by.

**Comment by adam-26** [comment]
@jvmlet, in response to your previous comment (that appears to be deleted?) I agree that using the FactoryBean<> approach is a preferred method of using dynamic interceptors.

However, I don't think using the `@Order()` annotation is an ideal solution. It results in interceptors not being portable across different projects (unless I'm mis-understanding how to correctly apply them?). Interceptor order if often important. Also if you have many interceptors configured developers need to inspect each interceptor file to determine the order that interceptors are executed.

If I: 
1. Remove the `getServiceInterceptors()` methods for applying service-specific interceptors.
2. Modify the PR `getServerInterceptors()` methods to return a list of `class`es instead of instantiated interceptors, that are applied globally, such as:

```java
public Collection<java.lang.Class<? extends io.grpc.ServerInterceptor>> getServerInterceptors() {
  return Arrays.asList(
          LogInterceptor.class
  );
}
```

Is this something you would accept?

**Comment by adam-26** [comment]
Closing

**Pull request closed without merging**
