### PR TITLE
optionally enable server reflection

### PR DESCRIPTION
**Pull request by jorgheymans**

### CODE REVIEW

**Comment by jvmlet** [comment]
Thanks @jorgheymans, would you please add few lines into Readme file about the feature and minimalistic unit test?

**Comment by jorgheymans** [comment]
I will have a look for a way to test this. 

Is the existing modification i did to README.adoc not sufficient?

**Comment by jvmlet** [comment]
Great, thanks. Do you need release build? I'll be able to publish it at Sunday, is it OK?

**Comment by jvmlet** [comment]
Got failed test, sometimes , 1 sec is not enough, had to fix it with [this](https://github.com/LogNet/grpc-spring-boot-starter/commit/a5bddc3a581ff9e12987fb229538d67bbac90cd9  )

**Pull request merged**
